(define (domain Resources)
	(:requirements :strips :typing)
    (:types pers loc)
	(:predicates (location ?loc - loc)
		     (person ?p - pers)
		     (person-at ?p - pers ?loc - loc)
		     (connected ?loc1 - loc ?loc2 - loc)
		     (active ?loc - loc))

	(:action move
	 :parameters (?p - pers ?l1 - loc ?l2 - loc)
	 :precondition (and (person ?p)
			    (person-at ?p ?l1)
			    (location ?l1)
			    (location ?l2)
			    (connected ?l1 ?l2)
			    (active ?l2))
	 :effect (and (person-at ?p ?l2)
	 	      (not (person-at ?p ?l1))
		      (not (active ?l2)))))
